NAME: DARN_open
SAVE_DIR: runs

INPUT:
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]

DATA:
  BASE_PATH: /local_data/zjw/data
  NUM_TRIPLETS: 100000
  TRAIN_BATCHSIZE: 16

MODEL:
  EMBED_SIZE: 512

SOLVER:
  BASE_LR: 2e-5
  EPOCHS: 20
  LOG_PERIOD: 20